### ISSUE TITLE
ndk filters

### ISSUE THREAD

**Issue by DanGdl** [hoangpq/rust-ndk-example#1]
Hi! Thanks for example, but on some devices (like samsung) app can't find .so file in runtime:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/packageName-68XSIyIbSaWUWPayGAm5-g==/base.apk"],nativeLibraryDirectories=[/data/app/packageName-68XSIyIbSaWUWPayGAm5-g==/lib/arm64, /system/lib64]]] couldn't find "librust.so"

I fixed it in this way (add in module's build.gradle ndk tag with filters):
android {
    ...
    defaultConfig {
       ...
        ndk {
            abiFilters "armeabi", "arm64", "x86"
        }
    }
}

**Comment by hoangpq** [comment]
Thanks @DanGdl, resolved #2
